"""add body_html

Revision ID: b951787c55c2
Revises: None
Create Date: 2019-03-16 20:10:12.802028

"""

# revision identifiers, used by Alembic.
revision = 'b951787c55c2'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    op.alter_column('posts', 'body',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('posts', 'post_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_posts_post_date'), 'posts', ['post_date'], unique=False)
    op.alter_column('project_req', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_project_req_email'), 'project_req', ['email'], unique=True)
    op.create_index(op.f('ix_project_req_full_name'), 'project_req', ['full_name'], unique=True)
    op.drop_constraint('project_req_email_key', 'project_req', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('project_req_email_key', 'project_req', ['email'])
    op.drop_index(op.f('ix_project_req_full_name'), table_name='project_req')
    op.drop_index(op.f('ix_project_req_email'), table_name='project_req')
    op.alter_column('project_req', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_posts_post_date'), table_name='posts')
    op.alter_column('posts', 'post_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('posts', 'body',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###